---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

## Load packages and set the environment

```{r}
#if(!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("Maaslin2")
library(Maaslin2)
library(here)
here()
```

## Fit MaAsLin2 linear multivariate model to SRS-normalized, collapsed feature table at genus level
Taxonomic filter has been applied to remove nonsense taxa. Singletons have been removed and features have been collapsed to genus level.
```{r, message=FALSE,warning=FALSE,results='hide',fig.keep='all'}
Maaslin2(here("results/dadatab-onlysamples-finalFiltered-srs-collapsed-transp.tsv"),
                     here("data/metadata_samples_Q2_nospaces.tsv"),
                     here("results/MaAsLin2/srs_collapsed_LogTransform_dose"),
         fixed_effects = 'dose_mg_per_kg',
         min_abundance = 100,
         min_prevalence = 0.4,
         normalization = "NONE",
         transform = "LOG",
         analysis_method = "LM",
         max_significance = 0.20,
         standardize = TRUE)
```   

